version: '3.8'

services:
  db:
    image: postgres:17.5
    restart: always
    env_file: 
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - PGPORT=5432
      - POSTGRES_DB=blog_db
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=alb3[8Dlk'tiE8@R+'1hCp~iP#9WKEGg.=SNySk^^-40t|jm
    volumes:
      - db-data:/var/lib/postgresql/data
      
  api:
    build: .
    command: >
      sh -c "python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          gunicorn Blog.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/app
    depends_on:
      - db

  nginx:
      build: ./nginx
      volumes:
        - ./static:/app/static
        - ./media:/app/media
      ports:
        - 81:80
      depends_on:
        - api

volumes:
  db-data: