# Generated by Django 5.2 on 2025-04-26 09:05

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="body",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 26, 9, 5, 44, 698578)
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(default="fake@email.com", max_length=254),
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(default="name", max_length=128),
        ),
    ]
