# Generated by Django 5.2 on 2025-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0003_rename_comment_comment_body_comment_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
