# Generated by Django 5.2 on 2025-04-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0004_alter_comment_created_on_alter_comment_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
